blank_issues_enabled: false
contact_links:
  - name: Soporte Zona Sur Tech
    url: mailto:soporte@zonasurtech.online
    about: Usa este canal para temas de soporte o seguridad que no deban ir en público.
